language: node_js
node_js:
    - "4"

branches:
    only:
        - develop
env:
    global:
        - PATH=${PATH}:node_modules/.bin

install:
    - npm --prefix backend install

before_script:
    - npm --prefix backend run build
    - npm --prefix backend run start&

script:
    - npm --prefix backend run test
    - npm --prefix backend run eslint
    - npm --prefix backend run doc

after_script:
    - source .travis/version.sh
    - source .travis/release.sh
