language: node_js
node_js:
    - "4"

branches:
    only:
        - develop
env:
    global:
        - PATH=${PATH}:node_modules/.bin
        - BUILD_FILES="backend/dist backend/server.js backend/package.json backend/npm_global_module_list"
        - REPORT_FILES="backend/api backend/reports"

before_install:
    - source .travis/prepare_git.sh

install:
    - npm --prefix backend install

before_script:
    - npm --prefix backend run build
    - npm --prefix backend run start&

script:
    - npm --prefix backend run test
    - npm --prefix backend run eslint
    - npm --prefix backend run doc

after_success:
    - source .travis/version.sh
    - source .travis/release.sh

after_script:
    - source .travis/publish_reports.sh
